CREATE TABLE IF NOT EXISTS owner (
    id  UUID PRIMARY KEY NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    active BOOLEAN NOT NULL,
    created_by VARCHAR(60),
    updated_by VARCHAR(60),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);